# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to=b'Files'),
        ),
    ]
